//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hasaki.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAOTRI
    {
        public int MaXe { get; set; }
        public int MaHD { get; set; }
        public Nullable<System.DateTime> NgayBaoTri { get; set; }
        public string NoiDungBT { get; set; }
    
        public virtual XE XE { get; set; }
        public virtual XE XE1 { get; set; }
        public virtual XE XE2 { get; set; }
    }
}
