//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hasaki.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETPHIEUNHAP
    {
        public int MaPN { get; set; }
        public int MaXe { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<double> DonGia { get; set; }
        public Nullable<double> TongTien { get; set; }
    
        public virtual PHIEUNHAP PHIEUNHAP { get; set; }
        public virtual PHIEUNHAP PHIEUNHAP1 { get; set; }
        public virtual PHIEUNHAP PHIEUNHAP2 { get; set; }
        public virtual XE XE { get; set; }
        public virtual XE XE1 { get; set; }
        public virtual XE XE2 { get; set; }
    }
}
