//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hasaki.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        public System.DateTime NGAY { get; set; }
        public string MASP { get; set; }
        public string MAKH { get; set; }
        public Nullable<int> SOLUONG { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual KHACHHANG KHACHHANG1 { get; set; }
        public virtual KHACHHANG KHACHHANG2 { get; set; }
        public virtual KHACHHANG KHACHHANG3 { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
